### ISSUE TITLE
Not work in newEdge

### ISSUE THREAD

**Issue by Todesstalker** [gautamkrishnar/motrix-webextension#10]
hi, I install this in newEdge, every step of the way, but can't intercept download URL.

**Comment by gautamkrishnar** [comment]
@Todesstalker As of now, I am not planning to support edge, When we have the MVP that is working, we can port it to other browsers.

**Comment by gautamkrishnar** [comment]
@149segolte Thanks a lot for investigating. Feel free to open a PR with a fix if this works out.

**Comment by 149segolte** [comment]
Resolved by #13

**Comment by gautamkrishnar** [comment]
@Todesstalker Please try out the latest release and let us know the feedback.

**Comment by Todesstalker** [comment]
Now it's working in NewEdge, Thank you for your efforts.

Gautam krishna R <notifications@github.com> 于2020年7月12日周日 下午3:45写道：
