### ISSUE TITLE
will there be a custom RPC port option other than 16800?

### ISSUE THREAD

**Issue by candrapersada** [gautamkrishnar/motrix-webextension#104]
will there be an option to use a custom port other than 16800 in Motrix WebExtension?
![image](https://user-images.githubusercontent.com/36833664/187416198-dd5dcf2d-d3d2-4352-97ed-af53f9ec27c4.png)

**Comment by gautamkrishnar** [comment]
Thanks for reminding, @candrapersada This is already fixed on #122 and will be available in a while when Google/Mozilla approves the release.

**Comment by berezovskyi** [comment]
Just tested 23.5.5 on Opera with `yarn run build opera` and works fine again! Thanks!
