### ISSUE TITLE
RPC Key Warning does not Display in some browsers (e.g. Background.js can only prompt a Console warning in Firefox)

### ISSUE THREAD

**Issue by AyoungDukie** [gautamkrishnar/motrix-webextension#107]
Some user confusion about the extension not working seems to be around the requirement for using and RPC Secret/Key.

Currently the extension will try to warn a user if they do not set a key by using `alert` in the background.js script. This works for Chrome (and likely other Chromium browser):
![image](https://user-images.githubusercontent.com/5449443/196060604-23d782f1-1cfb-4127-8f5d-0acf455b0126.png)

However Firefox security settings block alerts from background windows/activity, so the only notice is in the browser console:
![image](https://user-images.githubusercontent.com/5449443/196060649-67ade687-48d9-47f9-acdd-cea994d10018.png)

Looking into this, some recommendations are to use [notifications ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Notifications) instead (which will be supported in all browsers). Usually the downside is having to request a new permission, but notifications are already being used so it will be a non-issue. Secondarily, a notification will be less front-and-center, and could theoretically be missed. 

Conversely some folks have had success injecting the alert into the active tab, but this has some limitations.

[There's a decent write-up on SO about this.](https://stackoverflow.com/questions/38950281/need-workaround-for-calling-alert-from-background-script)

**Comment by gautamkrishnar** [comment]
@AyoungDukie thanks for the suggestion, i will work on this.
