### ISSUE TITLE
Documentation on Blacklist Syntax

### ISSUE THREAD

**Issue by AyoungDukie** [gautamkrishnar/motrix-webextension#109]
Just wanted to ask if there would be a preferred way to add documentation about using the Blacklist feature. Currently things are a tad open-ended because many similar extensions use differing ways to fill in these rules, and it could be helpful to have something telling users how to properly do so here.

To summarize what I believe I understand after looking into the scripts some:
 - The Blacklist uses linebreaks (`\n`) to define separate entries (some other extensions use space- or comma-separated entries)
 - The Blacklist seems able to handle a mix of full URLs and file extensions (some other extensions define these with different/separate settings)
 - For file extensions, including a period or `*` (wildcard) seems to break the entry, so just using the extension without other characters would be preferred

These were the main ones that I have come across so far, but I'm sure there are others, and having this in writing somewhere seems like a good idea. I'd be happy to make a PR in whatever way is preferred! 

Thanks again!

**Comment by TeusDev** [comment]
bump

**Comment by gautamkrishnar** [comment]
@AyoungDukie @TeusDev sorry for missing the issue. Feel free to open PR with the settings page here: https://github.com/gautamkrishnar/motrix-webextension/blob/master/app/scripts/config.js

**Comment by AyoungDukie** [comment]
Okay, I think the simplest solution to start is using the `helperText` property of the `TextField`; but it would probably be a good idea to also add a documentation page that can be linked to for more formal/full explanations.

Pull request is here https://github.com/gautamkrishnar/motrix-webextension/pull/110

**Comment by AyoungDukie** [comment]
With that merge complete, I have made a follow-up pull request to add a new documentation file for info on the settings https://github.com/gautamkrishnar/motrix-webextension/pull/111

I think once completed, we can close this issue!

Thanks for working through these!

**Comment by gautamkrishnar** [comment]
@AyoungDukie thanks for contributing ⭐

**Comment by AyoungDukie** [comment]
Glad to be able to help!
