### ISSUE TITLE
Support for other browsers?

### ISSUE THREAD

**Issue by 149segolte** [gautamkrishnar/motrix-webextension#12]
I opened this issue to discuss support for other browsers. Primarily,

- Edge ( Chromium based )
- Firefox

**Comment by 149segolte** [comment]
Both Edge and Firefox support WebExtensions API but while Edge supports Chrome extensions natively, Firefox requires browser-specific settings. Converting this project to WebExtensions based will allow us to support most of the modern browsers. Even Apple has announced support for WebExtensions in WWDC 2020.

@gautamkrishnar, But this will require a drastic change in the structure of the project, I could create a PR for this but would like your opinion for you might want to keep this as chrome only and I could continue the work in a fork.

**Comment by gautamkrishnar** [comment]
@149segolte That would be great. Please open a PR to [webextension-migration](https://github.com/gautamkrishnar/motrix-chrome-extension/tree/webextension-migration) branch since the project's repo name and readme should be updated after this.

**Comment by 149segolte** [comment]
Resolved by #13.
