### ISSUE TITLE
No longer working with Motrix Version 1.8.xx onwards

### ISSUE THREAD

**Issue by unluckydog** [gautamkrishnar/motrix-webextension#122]
The web extension needs an update. The motrix application now has new settings, so in addition to requiring a RPC secret key, there is now a port number that the user needs to specify (for example Port number 18625). 

Motrix's JSON-RPC port is by default 16800. You cannot change this setting in the current version of the web extension, but even at default settings Motrix doesn't automatically pick up downloads from Chrome.

**Comment by gautamkrishnar** [comment]
@unluckydog thanks for reporting this. Looks like an enhancement. Will add it.

**Comment by candrapersada** [comment]
related to #104
