### ISSUE TITLE
[Feature] Download file using Browser if Motrix is not open

### ISSUE THREAD

**Issue by Heus-Sueh** [gautamkrishnar/motrix-webextension#123]
Motivation: 
Edit: it ends up being frustrating when you want to download a file but he doesn't find the motrix open

Proposal:
Download file using Browser itself if Motrix is not open

**Comment by gautamkrishnar** [comment]
@Heus-Sueh as it is stated in the readme it is required to keep motrix open. There is no way for the extension to open motrix automaticallu: 
https://github.com/gautamkrishnar/motrix-webextension
![Screenshot 2023-05-06 at 8 32 34 PM](https://user-images.githubusercontent.com/8397274/236632108-7d053d62-ee3c-4dfc-a75b-094de75e073b.png)

**Comment by Heus-Sueh** [comment]
sorry i wasn't clear enough in the explanation i updated my issue description

**Comment by gautamkrishnar** [comment]
@Heus-Sueh thanks. It is already implemented on https://github.com/gautamkrishnar/motrix-webextension/pull/120 which is now availabele for chrome. Can you please check if it is working?

**Comment by Heus-Sueh** [comment]
sorry for the delay in replying, i was trying to test if this #120 was working but the extension stopped working here in my browser

**Comment by gautamkrishnar** [comment]
@Heus-Sueh Which browser are you using?

**Comment by Heus-Sueh** [comment]
> @Heus-Sueh Which browser are you using? it works fine for me on chrome.

I'm using librewolf, I think there was some bug in the browser here but it's back working, #120 doesn't seem to work at least not on linux

**Comment by gautamkrishnar** [comment]
This extension won't support libre wolf officially, Please try using Firefox instead. Also it needs to be on the latest version since i recently migrated to manifest v3.
