### ISSUE TITLE
Function request: add "download with Motrix" to the right-click menu

### ISSUE THREAD

**Issue by BOZHENG001** [gautamkrishnar/motrix-webextension#127]
Through this post, I would like to discuss the possibility of adding "download with Motrix" to the right-click menu in Chrome/browsers.

Currently, the Motrix web extension does not seem to support this function. Is it possible to include this function in future work?

Thanks for your consideration in advance.

**Comment by gautamkrishnar** [comment]
<img width="454" alt="Screenshot 2023-06-29 at 6 40 06 PM" src="https://github.com/gautamkrishnar/motrix-webextension/assets/8397274/1951fa46-546e-43bc-b2df-0a162122f943">
There is already a feature like this

**Comment by LSP0123** [comment]
it's not run on Edge(114.0.1823.67),and the extension is also not run as expected on Edge
![image](https://github.com/gautamkrishnar/motrix-webextension/assets/31061624/1b87e3cd-faa4-420a-a234-ab051d53ce69)

**Comment by BOZHENG001** [comment]
@gautamkrishnar Thanks for your instant reply. However, the feature is not working as expected. After clicking the "Download with Motrix", Chrome shows its own download screen, instead of the download screen of Motrix. Or maybe I am using the feature in the wrong way? Thanks in advance for taking care of this issue.
