### ISSUE TITLE
Web extension is not transferring the download task to motrix downloader app in m2

### ISSUE THREAD

**Issue by devggez** [gautamkrishnar/motrix-webextension#137]
{
  Browser : Brave
  device : m2 air
}

i have set RPC secret and RCP in extension and downloader, but it still not working

**Comment by gautamkrishnar** [comment]
@devggez brave is not officially supported by this browser extension.

**Comment by qtqgyt** [comment]
> [@devggez](https://github.com/devggez) brave is not officially supported by this browser extension.

To be fair, brave is essentially just chrome as it's core. I have used brave just fine.
