### ISSUE TITLE
Feature Request : Option to click on downloaded file to open it

### ISSUE THREAD

**Issue by TheOverpassArsonist** [gautamkrishnar/motrix-webextension#139]
In the default chrome download panel if you click it and then click on a downloaded file it will open that file in it's default application, but the motrix panel doesn't immitate that functionality and as far as I can tell there isn't anyway to enable it. It's minor but it's definitely noticable as a missing bit of QoL when using the extension for everyday downloads.

**Comment by gautamkrishnar** [comment]
@TheOverpassArsonist just checked this. Unfortunately due to browser's security policies opening files is not possible via a web extensions,
