### ISSUE TITLE
Ask before download for change filename?

### ISSUE THREAD

**Issue by candrapersada** [gautamkrishnar/motrix-webextension#17]
Ask before download for change filename and change download location file?

**Comment by spider623** [comment]
so i was not going crazy, the option "is" missing

**Comment by candrapersada** [comment]
[Critical!] Add a confirmation box before downloading from chrome and firefox plz! #33

**Comment by gautamkrishnar** [comment]
a fix for this is released on https://github.com/gautamkrishnar/motrix-webextension/releases/tag/21.10.5 please update the extension via webstores
