### ISSUE TITLE
Option to disable download notification

### ISSUE THREAD

**Issue by kotx** [gautamkrishnar/motrix-webextension#27]
#2 suggests to add a download notification, but Motrix itself already displays one when it finishes a download. This can be annoying for small files as I have to wait or dismiss the browser notification before clicking on the Motrix notification to open the downloaded file.

**Comment by JaroslawPokropinski** [comment]
I think this should be closed as https://github.com/gautamkrishnar/motrix-webextension/pull/41 implements that.

**Comment by gautamkrishnar** [comment]
Yes you are right @JaroslawPokropinski  👍🏻  thanks
