### ISSUE TITLE
Download gets started automaticially when the saves an image file

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/motrix-webextension#3]
- Right-click an image
- Click on save image as

The download is started automatically... This should be prevented.

**Comment by jewel-snake** [comment]
chrome.downloads has event onDeterminingFilename. As possible solution, you can make your code 
 wait until user finish choosing filename and destination directory.

**Comment by hthre7** [comment]
https://github.com/agalwood/Motrix/pull/716#issue-437359352

motrix add scheming this will actually
```
// New Task
motrix://new-task?uri=URL&out=NAME&dir=DIR

// Add Task silently, no confirmation
motrix://new-task?uri=URL&out=NAME&silent=true

// Open Preference
motrix://preferences

// Open About
motrix://about
```

**Comment by JaroslawPokropinski** [comment]
Is this not fixed by https://github.com/gautamkrishnar/motrix-webextension/pull/46?

**Comment by gautamkrishnar** [comment]
Yep this is fixed

**Comment by gautamkrishnar** [comment]
@hthre7 Thanks for letting us know. Let us see what we can change in the extension using the new scheme.
