### ISSUE TITLE
Does it work on Brave?

### ISSUE THREAD

**Issue by mizzunet** [gautamkrishnar/motrix-webextension#30]
I cannot see API option in Brave after loading the extension, this extension support Brave as well, doesn't it?
![Screenshot (3)](https://user-images.githubusercontent.com/10193999/113540081-f6368f00-95fc-11eb-81e5-7b8b56709d3d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/10193999/113540086-f8005280-95fc-11eb-96d6-cef9b8e4f0e8.png)

**Comment by brackenhill-mob** [comment]
Works fine for me on Arch Linux and Brave
