### ISSUE TITLE
Why don't package it into a .crx file?

### ISSUE THREAD

**Issue by Danny-Yxzl** [gautamkrishnar/motrix-webextension#32]
https://cloud.yixiangzhilv.com/api/v3/file/source/97/Motrix%E6%8B%A6%E6%88%AAchrome.crx?sign=EeLdpXYNuPdvDgPJhOkaeQ6bCAwrA17InFEqwOQEAPY%3D%3A0

**Comment by gautamkrishnar** [comment]
@Danny-Yxzl please use the latest extension from chrome or firefox portal https://github.com/gautamkrishnar/motrix-webextension/releases/tag/21.9.20
