### ISSUE TITLE
Ask before downloading

### ISSUE THREAD

**Issue by peterfat1** [gautamkrishnar/motrix-webextension#34]
So I always like chrome to ask me before download anything to avoid download malware, or any bad things. So, I think motrix should give a window about whether I want to download before downloading, like that IDM do.

Anyways thanks for such a good program!.

**Comment by gautamkrishnar** [comment]
A fix for this is released on https://github.com/gautamkrishnar/motrix-webextension/releases/tag/21.10.5

**Comment by FoRKsH** [comment]
I still have this issue
and enable `Prompt before download` makes edge use it's default downloader
