### ISSUE TITLE
Please update the plugin

### ISSUE THREAD

**Issue by cddehsy** [gautamkrishnar/motrix-webextension#38]
The plugin needs to be updated, there are so many problems, it doesn't capture links, and when it does it errors out and can't be downloaded. Would like to update to the browser extension shop.

**Comment by Rmdhn1** [comment]
pdf also has issues

**Comment by gautamkrishnar** [comment]
This extension is already published to chrome webstore right now. Please check the readme for links. @cddehsy Can you please elaborate on what error you are facing?

**Comment by gautamkrishnar** [comment]
Closing since this is deployed to chrome webstore
