### ISSUE TITLE
Please make this extension available on Chrome Web Store.

### ISSUE THREAD

**Issue by clicky6** [gautamkrishnar/motrix-webextension#39]
Please make this extension available on Chrome Web Store so that it is easy for a normal user also to use this extension.

**Comment by SGPublic** [comment]
This extension is already available on Chrome Web Store:
https://chrome.google.com/webstore/detail/moxtrix-webextension/ahmbonikfjldgaaccclamgkdhkpcppbn
#15

**Comment by gautamkrishnar** [comment]
@SGPublic that is not an official published copy of the extension. I just sent out an email to the person who submitted the extension to the store. I am now waiting for his/her reply. I will publish the extension myself once I have access.

**Comment by gautamkrishnar** [comment]
Just submitted the official version to the stores. Waiting for them to approve now.

**Comment by clicky6** [comment]
> Just submitted the official version to the stores. Waiting for them to approve now.

When it gets done add the link of the extension to readme.md .

**Comment by gautamkrishnar** [comment]
@clicky6 it is already there in the develop branch. Once the extension is approved, I will make it live.

**Comment by gautamkrishnar** [comment]
Extension is now live in the firefox webstore

**Comment by gautamkrishnar** [comment]
This extension is now available in all webstores https://github.com/gautamkrishnar/motrix-webextension

**Comment by swift-lee** [comment]
and also hope this extension can be available in Edge Extension Store, due to it is not very convenient for users in China to access the Chrome Web Store. Thanks!
