### ISSUE TITLE
Version 21.09.03 occasionally fails to capture file downloads

### ISSUE THREAD

**Issue by cddehsy** [gautamkrishnar/motrix-webextension#45]
Version 21.09.03 occasionally fails to capture file downloads，

**Comment by gautamkrishnar** [comment]
@cddehsy this was a known bug even in the old versions. Most authenticated file downloads will fail. I am still not sure how to solve this problem. Trying out different kinds of stuff.

**Comment by gautamkrishnar** [comment]
@cddehsy can you please try the latest version and share your feedback.

**Comment by cddehsy** [comment]
@gautamkrishnar Currently onedrive download failed, others seem to capture the download normally
