### ISSUE TITLE
edge load uncompressed extension shows error list file missing or unreadable

### ISSUE THREAD

**Issue by cddehsy** [gautamkrishnar/motrix-webextension#51]
edge load uncompressed extension shows error list file missing or unreadable

**Comment by gautamkrishnar** [comment]
@cddehsy did you do `yarn build chrome` before importing on edge?

**Comment by gautamkrishnar** [comment]
@cddehsy please install via https://chrome.google.com/webstore/detail/motrix-webextension/djlkbfdlljbachafjmfomhaciglnmkgj this is the recommended method.
