### ISSUE TITLE
There are plug-ins in Edge that need to be updated, I don't know if it's the one you released

### ISSUE THREAD

**Issue by cddehsy** [gautamkrishnar/motrix-webextension#58]
https://microsoftedge.microsoft.com/addons/detail/moxtrix-webextension/cippeolfnaoolpljklgcccckmilehbfg?hl=zh-CN

**Comment by gautamkrishnar** [comment]
It was not released by me. Please use https://chrome.google.com/webstore/detail/motrix-webextension/djlkbfdlljbachafjmfomhaciglnmkgj instead
