### ISSUE TITLE
Make these buttons a bit better.

### ISSUE THREAD

**Issue by clicky6** [gautamkrishnar/motrix-webextension#61]
Make these buttons from these:-
![3](https://user-images.githubusercontent.com/89839714/137594642-e765f9f8-a783-4fa4-a807-80fbad88bee6.png)
To something like this:-
![2](https://user-images.githubusercontent.com/89839714/137594679-5ab65448-71fa-4a57-9600-6198df58b272.png)
This will make the interface look and feel a lot more better.
And also change the color of buttons, Make it somewhat blue like shown in the above image.
Because violet doesn't look that much good.
These changes will give the extension a fluent (windows-11) look.

**Comment by gautamkrishnar** [comment]
@clicky6 this was fixed, will be released soon.
