### ISSUE TITLE
How to block the plugin to download pdf files?

### ISSUE THREAD

**Issue by 8ar10der** [gautamkrishnar/motrix-webextension#88]
I try to add `*.pdf` in the blacklist, but it is not work. All the pdf files will be download via this extension or I have to turn off this extension a while.

**Comment by JaroslawPokropinski** [comment]
Right now you can only limit using file URL or file size. If the pdfs you are referring to have URLs like https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf then you can add `.pdf` to blacklist (without star)

**Comment by 8ar10der** [comment]
> Right now you can only limit using file URL or file size. If the pdfs you are referring to have URLs like https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf then you can add `.pdf` to blacklist (without star)

Thanks!
