### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 1159591549** [gautamkrishnar/motrix-webextension#89]
who can tell me distinction that filename are AriaDownloader.js and BrowserDownloader.js ?（谁能告诉我AriaDownloader.js 和BrowserDownloader.js文件名的区别）

**Comment by 1159591549** [comment]
My wechat is it_boy_0713

**Comment by JaroslawPokropinski** [comment]
The BrowserDownloader.js handles downloads using your browser (it will add the item to the list in extension popup but file is still downloaded through browser). AriaDownloader.js uses aria (so for example your motrix) which can be much faster for bigger files.
